apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: dy2aucqj6-nodejs 
  janus-idp.io/tekton: dy2aucqj6-nodejs
  backstage.io/kubernetes-id: dy2aucqj6-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: dy2aucqj6-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml