apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: dy2aucqj6-nodejs
  janus-idp.io/tekton: dy2aucqj6-nodejs
  backstage.io/kubernetes-id: dy2aucqj6-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: dy2aucqj6-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
